## CARICAMENTO DB

In [2]:
# importazione pandas
import pandas as pd

In [3]:
# caricamento dataset
Hotel_Rev = pd.read_csv('Hotel_Reviews.csv')

## EDA

In [4]:
#visualizzazione delle prime 5 righe del dataset
Hotel_Rev.head(2)

,Hotel_Address,Additional_Number_of_Scoring,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,lat,lng
0,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,8/3/2017,7.7,Hotel Arena,Russia,I am so angry that i made this post available...,397,1403,Only the park outside of the hotel was beauti...,11,7,2.9,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,52.360576,4.915968
1,s Gravesandestraat 55 Oost 1092 AA Amsterdam ...,194,8/3/2017,7.7,Hotel Arena,Ireland,No Negative,0,1403,No real complaints the hotel was great great ...,105,7,7.5,"[' Leisure trip ', ' Couple ', ' Duplex Double...",0 days,52.360576,4.915968

In [5]:
# Riepilogo statistico completo, includendo tutte le colonne del df
Hotel_Rev.describe(include='all')

,Hotel_Address,Additional_Number_of_Scoring,Review_Date,Average_Score,Hotel_Name,Reviewer_Nationality,Negative_Review,Review_Total_Negative_Word_Counts,Total_Number_of_Reviews,Positive_Review,Review_Total_Positive_Word_Counts,Total_Number_of_Reviews_Reviewer_Has_Given,Reviewer_Score,Tags,days_since_review,lat,lng
count,515738,515738.000000,515738,515738.000000,515738,515738,515738,515738.000000,515738.000000,515738,515738.000000,515738.000000,515738.000000,515738,515738,512470.000000,512470.000000
unique,1493,NaN,731,NaN,1492,227,330011,NaN,NaN,412601,NaN,NaN,NaN,55242,731,NaN,NaN
top,163 Marsh Wall Docklands Tower Hamlets London ...,NaN,8/2/2017,NaN,Britannia International Hotel Canary Wharf,United Kingdom,No Negative,NaN,NaN,No Positive,NaN,NaN,NaN,"[' Leisure trip ', ' Couple ', ' Double Room '...",1 days,NaN,NaN
freq,4789,NaN,2585,NaN,4789,245246,127890,NaN,NaN,35946,NaN,NaN,NaN,5101,2585,NaN,NaN
mean,NaN,498.081836,NaN,8.397487,NaN,NaN,NaN,18.539450,2743.743944,NaN,17.776458,7.166001,8.395077,NaN,NaN,49.442439,2.823803
std,NaN,500.538467,NaN,0.548048,NaN,NaN,NaN,29.690831,2317.464868,NaN,21.804185,11.040228,1.637856,NaN,NaN,3.466325,4.579425
min,NaN,1.000000,NaN,5.200000,NaN,NaN,NaN,0.000000,43.000000,NaN,0.000000,1.000000,2.500000,NaN,NaN,41.328376,-0.369758
25%,NaN,169.000000,NaN,8.100000,NaN,NaN,NaN,2.000000,1161.000000,NaN,5.000000,1.000000,7.500000,NaN,NaN,48.214662,-0.143372
50%,NaN,341.000000,NaN,8.400000,NaN,NaN,NaN,9.000000,2134.000000,NaN,11.000000,3.000000,8.800000,NaN,NaN,51.499981,0.010607
75%,NaN,660.000000,NaN,8.800000,NaN,NaN,NaN,23.000000,3613.000000,NaN,22.000000,8.000000,9.600000,NaN,NaN,51.516288,4.834443
max,NaN,2682.000000,NaN,9.800000,NaN,NaN,NaN,408.000000,16670.000000,NaN,395.000000,355.000000,10.000000,NaN,NaN,52.400181,16.429233

In [6]:
#verifica totale righe e colonne che compongono il database
Hotel_Rev.shape

(515738, 17)

In [7]:
#Visualizzazione di informazioni sul databse e sulle colonne e i tipo di dati contenuti
Hotel_Rev.info()

<class 'pandas.DataFrame'>
RangeIndex: 515738 entries, 0 to 515737
Data columns (total 17 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   Hotel_Address                               515738 non-null  str
 1   Additional_Number_of_Scoring                515738 non-null  int64
 2   Review_Date                                 515738 non-null  str
 3   Average_Score                               515738 non-null  float64
 4   Hotel_Name                                  515738 non-null  str
 5   Reviewer_Nationality                        515738 non-null  str
 6   Negative_Review                             515738 non-null  str
 7   Review_Total_Negative_Word_Counts           515738 non-null  int64
 8   Total_Number_of_Reviews                     515738 non-null  int64
 9   Positive_Review                             515738 non-null  str
 10  Review_Total_Positive_Word_Counts           515738 non-null  int64
 11  Total_Number_of_Reviews_Reviewer_Has_Given  515738 non-null  int64
 12  Reviewer_Score                              515738 non-null  float64
 13  Tags                                        515738 non-null  str
 14  days_since_review                           515738 non-null  str
 15  lat                                         512470 non-null  float64
 16  lng                                         512470 non-null  float64
dtypes: float64(4), int64(5), str(8)
memory usage: 66.9 MB

In [8]:
# controllo se ci sono valori nulli
Hotel_Rev.isnull().sum()

Hotel_Address                                    0
Additional_Number_of_Scoring                     0
Review_Date                                      0
Average_Score                                    0
Hotel_Name                                       0
Reviewer_Nationality                             0
Negative_Review                                  0
Review_Total_Negative_Word_Counts                0
Total_Number_of_Reviews                          0
Positive_Review                                  0
Review_Total_Positive_Word_Counts                0
Total_Number_of_Reviews_Reviewer_Has_Given       0
Reviewer_Score                                   0
Tags                                             0
days_since_review                                0
lat                                           3268
lng                                           3268
dtype: int64

In [9]:
# controllo se ci sono dupplicati
Hotel_Rev.duplicated().sum()

np.int64(526)

In [10]:
#Dettagli sul campo valore "Reviewer_Score"
Hotel_Rev['Reviewer_Score'].describe()

count    515738.000000
mean          8.395077
std           1.637856
min           2.500000
25%           7.500000
50%           8.800000
75%           9.600000
max          10.000000
Name: Reviewer_Score, dtype: float64

In [11]:
#Dettagli sul campo valore "Average_Score"
Hotel_Rev['Average_Score'].describe()

count    515738.000000
mean          8.397487
std           0.548048
min           5.200000
25%           8.100000
50%           8.400000
75%           8.800000
max           9.800000
Name: Average_Score, dtype: float64

In [12]:
#Calcolo delle distribuzioni dei voti suddivise in fasce: 
Range_voti = [2.5,4,6,8,10]
Distribuzione_RS = Hotel_Rev['Reviewer_Score'].value_counts(bins=Range_voti).sort_index()
Distribuzione_AS = Hotel_Rev['Average_Score'].value_counts(bins=Range_voti).sort_index()

#Creazione di un df di confronto:
Confronto = pd.DataFrame({
    'Conteggio_Totale_Recensioni': Distribuzione_RS,
    'Conteggio_Hotel': Distribuzione_AS
    })

Confronto.index.name = "Intervallo voti"

print(Confronto)

                 Conteggio_Totale_Recensioni  Conteggio_Hotel
Intervallo voti
(2.499, 4.0]                           10812                0
(4.0, 6.0]                             41948               65
(6.0, 8.0]                            127837           116924
(8.0, 10.0]                           335141           398749

In [13]:
H_R_C = Hotel_Rev.copy()

# DATA CLEANING

### GESTIONE MISSING VALUES

In [14]:
#Cancellazione delle righe con i valori nulli 
H_R_C.dropna(inplace=True)

#controllo della pulizia se avvenuta correttamente
H_R_C.isnull().sum()

Hotel_Address                                 0
Additional_Number_of_Scoring                  0
Review_Date                                   0
Average_Score                                 0
Hotel_Name                                    0
Reviewer_Nationality                          0
Negative_Review                               0
Review_Total_Negative_Word_Counts             0
Total_Number_of_Reviews                       0
Positive_Review                               0
Review_Total_Positive_Word_Counts             0
Total_Number_of_Reviews_Reviewer_Has_Given    0
Reviewer_Score                                0
Tags                                          0
days_since_review                             0
lat                                           0
lng                                           0
dtype: int64

### CONVERSIONE IN DATETIME ED ESTRAZIONE ANNO/MESE

In [15]:
# Conversione colonna 'Review_Date' da str a Datetime
H_R_C['Review_Date'] = pd.to_datetime(H_R_C['Review_Date'])

#Estrazione dell'anno
H_R_C['Year'] = H_R_C['Review_Date'].dt.year

#Estrazione del mese
H_R_C['Month'] = H_R_C['Review_Date'].dt.month

#Verificazione dell'avvenuta modifica
print(H_R_C['Review_Date'].dtype)
print(H_R_C[['Review_Date', 'Year', 'Month']].head(4))

datetime64[us]
  Review_Date  Year  Month
0  2017-08-03  2017      8
1  2017-08-03  2017      8
2  2017-07-31  2017      7
3  2017-07-31  2017      7

In [16]:
#Rinominazione colonne 

H_R_C = H_R_C.rename(columns={
    'Total_Number_of_Reviews_Reviewer_Has_Given': 'Reviewer_Total_Reviews'})

### RIMOZIONE DUPLICATI ESATTI

In [17]:
# cancellazione delle righe con valori dupplicati
H_R_C.drop_duplicates(inplace=True)

# controllo della corretta avvenuta cancellazione
H_R_C.duplicated().sum()

np.int64(0)

### CREAZIONE VARIABILI DERIVATE

In [18]:
# Creazione prima colonna derivata dalla colonna 'Tags' tramite una funzione che in base
# alla parola chiave rilevata nella tag associa la recensione a una determinata categoria:

def identificazione_ospite(tag):
    tag_lower = str(tag).lower()
    
    if 'family' in tag_lower:
        return 'Family'
    elif 'couple' in tag_lower:
        return 'Couple'
    elif 'group' in tag_lower:
        return 'Group'
    elif 'solo' in tag_lower:
        return 'Solo'
    else:
        return 'Other'
    
# Creazione della nuova colonna
H_R_C['Guest_Category'] = H_R_C['Tags'].apply(identificazione_ospite)

In [19]:
# Creazione seconda colonna derivata dalla colonna 'Hotel_Address' tramite una funzione
# che in base alla ultima/penultima parola rilevata nell'indirizzo, restituisce nella nuova
# colonna il paese di appartenenza dell'hotel.

def estrazione_paese(indirizzo):
    parola = indirizzo.split()
    if "Kingdom" in indirizzo:
        return " ".join(parola[-2:])
    else:
        return parola[-1]
    
H_R_C['Hotel_Country'] = H_R_C['Hotel_Address'].apply(estrazione_paese)

In [20]:
# Creazione  terza colonna derivata dalla colonna 'Hotel_Address' tramite una funzione
# che in base alla parola precedente al pease, rilevata nell'indirizzo, restituisce nella nuova
# colonna la città di appartenenza dell'hotel

def estrazione_città(row):
    indirizzo = row['Hotel_Address']
    paese = row['Hotel_Country']
    
    # 1. Rimozione del nome del paese dall'indirizzo e degli spazi extra
    indirizzo_pulito = indirizzo.replace(paese, '').strip()
    parole = indirizzo_pulito.split()
    
    if paese == 'United Kingdom':
        # selezione delle ultime 3 parole (es: 'London W2 3NA') 
        # e tra queste tre la prima (London)
        if len(parole) >= 3:
            return parole[-3]
        return parole[0] # Fallback se l'indirizzo è corto
    else:
        # Per le altre nazioni: selezione dell'ultima parola rimasta dopo la rimozione del paese
        return parole[-1]

# Applicazione della funzione usando 'axis=1' poichè occorre sia Indirizzo che Paese
H_R_C['Hotel_City'] = H_R_C.apply(estrazione_città, axis=1)

In [21]:
# Esecuzione controllo per verificare che abbia associato alla nuova colonna
# solo valori corrispondenti a paesi e città nelle rispettive colonne:
print(H_R_C['Hotel_Country'].unique())
print(H_R_C['Hotel_City'].unique())

<StringArray>
['Netherlands', 'United Kingdom', 'France', 'Spain', 'Italy', 'Austria']
Length: 6, dtype: str
<StringArray>
['Amsterdam', 'London', 'Paris', 'Barcelona', 'Milan', 'Vienna']
Length: 6, dtype: str

In [22]:
# Controllo della corretta aggiunta delle 3 colonne derivate
H_R_C.info()

<class 'pandas.DataFrame'>
Index: 511944 entries, 0 to 515737
Data columns (total 22 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Hotel_Address                      511944 non-null  str
 1   Additional_Number_of_Scoring       511944 non-null  int64
 2   Review_Date                        511944 non-null  datetime64[us]
 3   Average_Score                      511944 non-null  float64
 4   Hotel_Name                         511944 non-null  str
 5   Reviewer_Nationality               511944 non-null  str
 6   Negative_Review                    511944 non-null  str
 7   Review_Total_Negative_Word_Counts  511944 non-null  int64
 8   Total_Number_of_Reviews            511944 non-null  int64
 9   Positive_Review                    511944 non-null  str
 10  Review_Total_Positive_Word_Counts  511944 non-null  int64
 11  Reviewer_Total_Reviews             511944 non-null  int64
 12  Reviewer_Score                     511944 non-null  float64
 13  Tags                               511944 non-null  str
 14  days_since_review                  511944 non-null  str
 15  lat                                511944 non-null  float64
 16  lng                                511944 non-null  float64
 17  Year                               511944 non-null  int32
 18  Month                              511944 non-null  int32
 19  Guest_Category                     511944 non-null  str
 20  Hotel_Country                      511944 non-null  str
 21  Hotel_City                         511944 non-null  str
dtypes: datetime64[us](1), float64(4), int32(2), int64(5), str(10)
memory usage: 85.9 MB

In [23]:
#Salvataggio di una copia in formato CSV del df manipolato
H_R_C.to_csv('hotel_reviews_clean.csv', index=False)

In [24]:
#Creazione db Hotels
Hotels = H_R_C[['Hotel_Name', 'Hotel_Address', 'Hotel_Country', 'Hotel_City']].drop_duplicates().reset_index(drop=True)
Hotels.insert(0, 'Hotel_ID', ['H' + str(i) for i in range(1, len(Hotels) + 1)])

Hotels.to_csv('Hotels.csv', index=False)

In [25]:
#Creazione db Reviewers
Reviewers = H_R_C[['Reviewer_Nationality', 'Guest_Category', 'Reviewer_Total_Reviews']].drop_duplicates().reset_index(drop=True)
Reviewers.insert(0, 'Reviewer_ID', ['Rr' + str(i) for i in range(1, len(Reviewers) + 1)])

Reviewers.to_csv('Reviewers.csv', index=False)

In [ ]:
#Creazione db Reviews

Reviews = H_R_C.copy()

colonne_identità_reviewer = ['Reviewer_Nationality', 'Guest_Category', 'Reviewer_Total_Reviews']
colonne_identità_hotel = ['Hotel_Name', 'Hotel_Address', 'Hotel_Country', 'Hotel_City']

# Collegamento dell'Hotel_ID corretto tramite il nome dell'hotel
Reviews = Reviews.merge(Hotels, on=colonne_identità_hotel, how='left')

# Collegamento del Reviewer_ID tramite la nazionalità (o altra colonna identificativa)
Reviews = Reviews.merge(Reviewers, on=colonne_identità_reviewer, how='left')

# Creazione l'ID univoco per ogni singola recensione
Reviews.insert(0, 'Review_ID', ['Rw' + str(i) for i in range(1, len(Reviews) + 1)])

In [ ]:
#Creazione db Hotel_Stats
Hotel_Stats = Reviews.copy()
Hotel_Stats = Hotel_Stats.drop(columns=['Positive_Review',	'Reviewer_Total_Reviews',	'Reviewer_Score', 'Review_ID', 'Hotel_Address', 'Review_Date',	'Hotel_Name',	'Reviewer_Nationality',	'Negative_Review',	'Review_Total_Negative_Word_Counts',	'Tags',	'Year',	'Month',	'Guest_Category',	'Hotel_Country',	'Reviewer_ID', 'Hotel_City'])

In [ ]:
H_S = Hotel_Stats.copy()




# 2. Creazione di una colonna temporanea numerica estraendo solo i numeri da '100 day'
H_S['days_numeric'] = H_S['days_since_review'].str.extract('(\d+)').astype(int)

# 3. Ordine del DataFrame: prima per Hotel_ID e poi per i giorni in modo decrescente
H_S_sorted = H_S.sort_values(by=['Hotel_ID', 'days_numeric'], ascending=[True, False])

# 4. Rimozione dei duplicati mantenendo solo la prima occorrenza (la più recente)
H_S_pulito = H_S_sorted.drop_duplicates(subset=['Hotel_ID'], keep='first')

# 5. Rimuozione dela colonna di supporto numerica per tornare alla struttura originale
H_S_pulito = H_S_pulito.drop(columns=['days_numeric'])

H_S_pulito.sort_values(by=['Hotel_ID'])

H_S_pulito.to_csv('Hotel_Stats.csv', index=False)

print(H_S_pulito.head(10))

<>:8: SyntaxWarning: invalid escape sequence '\d'
<>:8: SyntaxWarning: invalid escape sequence '\d'
C:\Users\salma\AppData\Local\Temp\ipykernel_32944\869288984.py:8: SyntaxWarning: invalid escape sequence '\d'
  H_S['days_numeric'] = H_S['days_since_review'].str.extract('(\d+)').astype(int)

        Additional_Number_of_Scoring  Average_Score  Total_Number_of_Reviews  \
244                              194            7.7                     1403
7662                              75            8.9                      486
37962                            139            8.4                     1184
344992                           237            8.4                     2179
345486                           196            8.4                     1992
345498                            18            9.4                       64
345767                           253            8.4                     2586
346385                           550            8.8                     4097
347125                           360            8.3                     1181
347490                            15            8.2                      139

        Review_Total_Positive_Word_Counts days_since_review        lat  \
244                                     4           730 day  52.360576
7662                                   20           728 day  48.874707
37962                                  23           716 day  48.871583
344992                                  5           730 day  52.310118
345486                                  4           730 day  52.309683
345498                                 30           663 day  51.503030
345767                                  9           730 day  52.358881
346385                                 18           730 day  52.384606
347125                                  0           730 day  51.475172
347490                                 15           149 day  41.383558

             lng Hotel_ID
244     4.915968       H1
7662    2.293676      H10
37962   2.322485     H100
344992  4.947292    H1000
345486  4.942261    H1001
345498 -0.152420    H1002
345767  4.988604    H1003
346385  4.894187    H1004
347125 -0.187063    H1005
347490  2.178311    H1006

In [ ]:
# Cancellazione delle colonne non appartenenti alla tabella Reviews
Reviews = Reviews.drop(columns=['Reviewer_Nationality', 'Guest_Category', 'Reviewer_Total_Reviews', 'Hotel_Name', 'Hotel_Address', 'Hotel_Country', 'Hotel_City', 'Additional_Number_of_Scoring', 'Average_Score', 'Total_Number_of_Reviews', 'days_since_review', 'lat', 'lng'])

Reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 511944 entries, 0 to 511943
Data columns (total 12 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Review_ID                          511944 non-null  str
 1   Review_Date                        511944 non-null  datetime64[us]
 2   Negative_Review                    511944 non-null  str
 3   Review_Total_Negative_Word_Counts  511944 non-null  int64
 4   Positive_Review                    511944 non-null  str
 5   Review_Total_Positive_Word_Counts  511944 non-null  int64
 6   Reviewer_Score                     511944 non-null  float64
 7   Tags                               511944 non-null  str
 8   Year                               511944 non-null  int32
 9   Month                              511944 non-null  int32
 10  Hotel_ID                           511944 non-null  str
 11  Reviewer_ID                        511944 non-null  str
dtypes: datetime64[us](1), float64(1), int32(2), int64(2), str(6)
memory usage: 43.0 MB

In [30]:
# controllo della corretta avvenuta cancellazione
Reviews.duplicated().sum()
#controllo della pulizia se avvenuta correttamente
Reviews.isnull().sum()

Review_ID                            0
Review_Date                          0
Negative_Review                      0
Review_Total_Negative_Word_Counts    0
Positive_Review                      0
Review_Total_Positive_Word_Counts    0
Reviewer_Score                       0
Tags                                 0
Year                                 0
Month                                0
Hotel_ID                             0
Reviewer_ID                          0
dtype: int64

In [31]:
#Salvataggio in csv 
Reviews.to_csv('Reviews.csv', index=False)

In [32]:
#Stampa dati per verifica incrociata
print('Totale Indirizzi hotel in H_R_C_: ', H_R_C['Hotel_Address'].nunique())
print('Totale indirizzi hotel in Hotels: ', Hotels['Hotel_Address'].nunique())
print("")
print('Totale hotel id in Hotels: ', Hotels['Hotel_ID'].nunique())
print('Totale hotel id in Hotel_Stats: ', Hotel_Stats['Hotel_ID'].nunique())
print('Totale hotel id in  Reviews: ', Reviews['Hotel_ID'].nunique())
print("")
print('Totale reviewer id in Reviewers: ', Reviewers['Reviewer_ID'].nunique())
print('Totale reviewer id in  Reviews: ', Reviews['Reviewer_ID'].nunique())

Totale Indirizzi hotel in H_R_C_:  1476
Totale indirizzi hotel in Hotels:  1476

Totale hotel id in Hotels:  1477
Totale hotel id in Hotel_Stats:  1477
Totale hotel id in  Reviews:  1477

Totale reviewer id in Reviewers:  16864
Totale reviewer id in  Reviews:  16864

In [33]:
Hotel_Stats.info()
print('Totale hotel id in Hotel_Stats: ', Hotel_Stats['Hotel_ID'].nunique())

<class 'pandas.DataFrame'>
RangeIndex: 511944 entries, 0 to 511943
Data columns (total 8 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Additional_Number_of_Scoring       511944 non-null  int64
 1   Average_Score                      511944 non-null  float64
 2   Total_Number_of_Reviews            511944 non-null  int64
 3   Review_Total_Positive_Word_Counts  511944 non-null  int64
 4   days_since_review                  511944 non-null  str
 5   lat                                511944 non-null  float64
 6   lng                                511944 non-null  float64
 7   Hotel_ID                           511944 non-null  str
dtypes: float64(3), int64(3), str(2)
memory usage: 31.2 MB
Totale hotel id in Hotel_Stats:  1477